# Generated by Django 5.0.6 on 2024-05-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_skillcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.skillcategory')),
            ],
        ),
    ]
