# Generated by Django 5.0.6 on 2024-05-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio_app.skillcategory'),
        ),
    ]
